### PR TITLE
Fix travis build and weekly stats report

### PR DESCRIPTION
**Pull request by tallenaz**

### CODE REVIEW

**Comment by darrenleeweber** [comment]
This looks good and I want to merge it.  The only hesitation is whether the previous gitignore for the test environment was there for a reason, because we are running an sdr-services-test system.  I started discussions about renaming this to sdr-services-stage many years ago, but it may not have happened.  Hence, there may be `test` configs that apply to that deployment target.

**Comment by darrenleeweber** [comment]
Checked whether the `develop` branch has an `environment/test.rb` file and I don't see one there
- https://github.com/sul-dlss/sdr-preservation-core/tree/develop/config/environments

But the develop branch does run on travis, so I wonder how that works?

**Comment by tallenaz** [comment]
I believe it has to do with how `boot.rb` is set up. [Here's a branch](https://github.com/sul-dlss/sdr-preservation-core/blob/fae0d7ddd1b2abe81e8404f3a2cebed78e9e2263/lib/boot.rb#L65-L66) where the boot configuration is made the same across `master` and `develop` branches and where travis builds of each branch pass. If this part of the boot config for `master` can remain the same as in `develop`, then no `test.rb` environment would be needed.

**Comment by tallenaz** [comment]
@darrenleeweber I went ahead and amended this PR with the simpler boot configuration change, assuming that what's good enough for `develop` is good enough for `master`.

**Pull request merged**
